name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - feature/TASK-285-CD-GitHub-Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Change to itp-front directory
        run: cd itp-front

      - name: Install dependencies
        run: npm ci
        working-directory: ./itp-front

      - name: Install Vue CLI
        run: npm install -g @vue/cli

      - name: Build the project
        run: npm run build
        working-directory: ./itp-front

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./itp-front/dist
            publish_branch: gh-pages
    
