name: Vue.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    # Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Change to the itp-front directory
    - name: Change to itp-front directory
      run: cd itp-front

    # Set up Node.js for the specific version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies using npm
    - name: Install dependencies
      run: npm ci
      working-directory: ./itp-front

    # Install Vue CLI globally if needed
    - name: Install Vue CLI
      run: npm install -g @vue/cli

    # Build the Vue.js project
    - name: Build the project
      run: npm run build
      working-directory: ./itp-front

    # Run tests for Vue.js application if applicable
    # Uncomment the following lines if you have tests set up
    # - name: Run tests
    #   run: npm test
    #   working-directory: ./itp-front
