name: Vue.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    # Install Vue CLI if needed
    - name: Install Vue CLI
      run: npm install -g @vue/cli

    # Run linting if you have lint script
    - name: Lint code
      run: npm run lint

    - run: npm run build

    - run: npm test
